### ISSUE TITLE
Logging infrastructure in 'SemMC.Formula.Load' blocked on MVar operation

### ISSUE THREAD

**Issue by jpaykin** [GaloisInc/semmc#14]
When loading the semantics for opcodes via 'loadFormulas', I get an exception: `thread blocked indefinitely in an MVar operation`.

``` haskell
import           Data.Proxy (Proxy(..))
import           Data.Parameterized.Some (Some(..))

import qualified Data.Parameterized.Nonce as PN
import           SemMC.Formula
import qualified SemMC.Architecture.PPC64 as PPC64
import qualified SemMC.Architecture.PPC64.Opcodes as PPC64
import qualified SemMC.Log as Log
import qualified Lang.Crucible.Backend.Online as Online

main :: IO ()
main = do
  logcfg <- Log.mkLogCfg "main"
  Log.withLogCfg logcfg $ do
    Some nonce <- PN.newIONonceGenerator
    Online.withZ3OnlineBackend @(Online.Flags Online.FloatReal) nonce Online.NoUnsatFeatures  $ \sym -> do
      let ppcSemantics = PPC64.allSemantics
      let ppcFunctions = PPC64.allDefinedFunctions
      lib <- loadLibrary (Proxy @PPC64.PPC) sym ppcFunctions
      semantics <- loadFormulas @_ @PPC64.PPC sym lib ppcSemantics
      return ()
```

The same behavior is exhibited using a `SimpleBackend` instead of `OnlineBackend`. I am using GHC 8.4.3.

The problem seems to arise from the logging infrastructure in `SemMC.Formula.Load.loadFormulas`  and `SemMC.Formula.Parse.readFormula'`. By commenting out the three calls to `SemMC.Log.logIO` in those functions, the error is avoided. Another workaround is to replace the call to `mkLogCfg` with `Log.mkNonLogCfg` which introduces a trivial configuration.

**Comment by travitch** [comment]
I think you might need to add a log consumer: can you try to spin up a thread (before loading any semantics files) that just calls e.g. `stdErrLogEventConsumer`?  Without that, I bet the threads trying to log are just getting killed.

**Comment by jpaykin** [comment]
Thanks @travitch, you're exactly right. The documentation on  `mkLogCfg` says:

```
-- Need to start a log event consumer in another thread,
-- e.g. 'stdErrLogEventConsumer', if you want anything to happen with
-- the log events.
```

I think I will amend that a bit to make it clear that without a consumer you will actually get an error, but really this was me not reading the documentation closely enough.
