### ISSUE TITLE
`stdu` stores the updated value rather than the old one

### ISSUE THREAD

**Issue by lukemaurer** [GaloisInc/semmc#15]
Most PPC functions have an instruction like this near the top:
```
stdu r1, -128(r1)
```
it's intended to store the old value of the stack pointer at the bottom of the new frame. The PPC specs (p. 57) say that the value of `r1` is read *before* it's updated with the effective address:

```
EA <- (RA) + EXTS(DS || 0b00)
MEM(EA, 8) <- (RS)
RA <- EA
```
SemMC seems to implement `stdu` as if the second and third lines are swapped, which is a problem when `RS` and `RA` are the same. The Crucible CFG code makes it pretty apparent that `EA` is what's stored in memory rather than `RS`:

```
  $21 = (macawWriteMem bvbe 8 $20 $20)
```

The effect, of course, is to store an address at its own location in memory, which is clearly not what's intended in every stack frame.

**Comment by travitch** [comment]
@dmwit Can you take a look at this if you have a chance?

**Comment by dmwit** [comment]
On it.
