### ISSUE TITLE
Switch from `itanium-abi` package to `demangler` package

### ISSUE THREAD

**Issue by kquick** [GaloisInc/semmc#84]
See https://github.com/GaloisInc/demangler.  The `demangler` package is both faster and also more complete with regards to demangling coverage (although still not 100%).

Potentially affecting https://github.com/GaloisInc/semmc/pull/83

**Comment by RyanGlScott** [comment]
This issue should probably live in the `crucible` repo, not here, since the `itanium-abi` depenency is found in `crucible-llvm` ([here](https://github.com/GaloisInc/crucible/blob/e86140641260b00f64fdbd51d73d48d766c55bdf/crucible-llvm/crucible-llvm.cabal#L46)).

**Comment by kquick** [comment]
Right: https://github.com/GaloisInc/crucible/issues/1235
